---
- name: Hardening Filesystem & Mount Options
  ansible.builtin.import_tasks: filesystem.yml

- name: Menonaktifkan Modul Kernel & Protokol Jaringan Tidak Digunakan
  ansible.builtin.import_tasks: kernel_modules.yml

- name: Hardening Kernel Parameters & Sysctl
  ansible.builtin.import_tasks: sysctl.yml

- name: Pengamanan Layanan & Pembersihan Paket Legacy
  ansible.builtin.import_tasks: services.yml

- name: Hardening Penjadwal Tugas Cron & At Daemon
  ansible.builtin.import_tasks: cron.yml

- name: Hardening OpenSSH Server Configuration
  ansible.builtin.import_tasks: ssh.yml

- name: Hardening Kebijakan Password & Otentikasi PAM
  ansible.builtin.import_tasks: auth.yml

- name: Hardening Host Firewall (Nftables) & Auditd Rules
  ansible.builtin.import_tasks: firewall_audit.yml

- name: Hardening Systemd Journald & Izin Berkas Log
  ansible.builtin.import_tasks: logging.yml

- name: Pengamanan Akses Sistem, Sudoers, Banners & Environment
  ansible.builtin.import_tasks: system_access.yml

- name: Integritas Sistem (AIDE), Bootloader GRUB & AppArmor
  ansible.builtin.import_tasks: integrity.yml
